# Generated by Django 3.2.6 on 2021-08-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('義大利麵', '義大利麵'), ('蛋料理', 'Egg Dishes'), ('Fried Dishes', 'Fried Dishes'), ('Rice Dishes', 'Rice Dishes')], max_length=100),
        ),
    ]
