# Generated by Django 3.2.6 on 2021-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('義大利麵', '義大利麵'), ('蛋料理', '蛋料理'), ('炸物與點心', '炸物與點心'), ('飯料理', '飯料理')], max_length=100),
        ),
    ]
