# Generated by Django 3.2.6 on 2021-08-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_meal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField()),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meal')),
            ],
        ),
    ]
