# Generated by Django 3.2.6 on 2021-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content',
            field=models.TextField(default=1234),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
