# Generated by Django 3.2.6 on 2021-08-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210818_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addedmeal'),
        ),
    ]
