# Generated by Django 3.2.6 on 2021-08-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(),
        ),
    ]
