# Generated by Django 3.2.6 on 2021-08-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('unitprice', models.PositiveIntegerField()),
                ('unit', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='cmail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='cphone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='orderno',
        ),
        migrations.DeleteModel(
            name='AddedMeal',
        ),
        migrations.AddField(
            model_name='ordermeal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
